# Generated by Django 5.1.7 on 2025-03-28 14:14

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='问答类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('update_date', models.DateTimeField(auto_created=True, verbose_name='更新时间')),
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('issueTitle', models.CharField(max_length=128, verbose_name='问答标题')),
                ('issueContent', models.TextField(max_length=10240, verbose_name='问答内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.issuetype')),
            ],
        ),
        migrations.CreateModel(
            name='Issue2Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issue', verbose_name='问答ID')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issuetype', verbose_name='问答类型ID')),
            ],
        ),
    ]
