# Generated by Django 5.1.7 on 2025-03-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_issue_commentnumber_issue_scannumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
    ]
