# Generated by Django 5.2 on 2025-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.ManyToManyField(to='issue.issuetype', verbose_name='评论关联的问答类型'),
        ),
    ]
