# Generated by Django 5.2 on 2025-04-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentType',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=1, verbose_name='评论类型'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.issue'),
        ),
    ]
