# Generated by Django 5.2 on 2025-04-11 10:45

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alter_comment_commenttype_alter_comment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentType',
            field=models.SmallIntegerField(choices=[(0, '问答'), (1, '书籍')], default=1, verbose_name='评论类型'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('quizTitle', models.CharField(max_length=128, verbose_name='考试题标题')),
                ('quizContent', models.TextField(max_length=10240, verbose_name='考试题内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issuetype')),
            ],
        ),
    ]
