# Generated by Django 5.2 on 2025-04-12 16:53

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_alter_comment_commenttype_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='书籍标题')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='book_imgs', verbose_name='书籍图片')),
                ('downloadLink', models.CharField(blank=True, max_length=512, null=True, verbose_name='书籍下载链接')),
                ('bookInfo', models.TextField(max_length=10240, verbose_name='书籍介绍')),
                ('requirePoints', models.IntegerField(default=0, verbose_name='书籍查看需要的分数')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issuetype', verbose_name='书籍对应的类型')),
            ],
        ),
    ]
