# Generated by Django 5.2 on 2025-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='commentNumber',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='book',
            name='scanNumber',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
