# Generated by Django 5.2 on 2025-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_book_commentnumber_book_scannumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
