# Generated by Django 5.2 on 2025-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_comment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentType',
            field=models.SmallIntegerField(choices=[(1, '问答'), (2, '书籍')], default=1, verbose_name='评论类型'),
        ),
    ]
