# Generated by Django 5.1.7 on 2025-03-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
