# Generated by Django 5.1.7 on 2025-03-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_rename_uid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', help_text='用户角色', max_length=10, verbose_name='用户角色'),
        ),
    ]
