# Generated by Django 5.2.8 on 2025-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True, help_text='后台页面权限', verbose_name='后台页面权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.IntegerField(default=1, help_text='后台页面权限', verbose_name='后台页面权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('admin', '管理员')], default='user', help_text='用户角色', max_length=10, verbose_name='用户角色'),
        ),
    ]
