# Generated by Django 6.0 on 2025-12-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_enabled_user_permission_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default='', help_text='用户介绍', max_length=1024, verbose_name='用户介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', help_text='用户QQ号', max_length=20, verbose_name='用户的QQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(default='', help_text='用户的微信号', max_length=60, verbose_name='用户的微信号'),
        ),
    ]
